# Generated by Django 4.1.4 on 2023-01-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_fav'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteAdv',
        ),
    ]
